import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {createController} from '../visual/phase4/web/controller.mjs';
const require=createRequire(import.meta.url),rive=require('../../node_modules/@rive-app/webgl2/rive.js');
const wasm=fs.readFileSync(new URL('../../node_modules/@rive-app/webgl2/rive.wasm',import.meta.url));rive.RuntimeLoader.setWasmBinary(wasm.buffer.slice(wasm.byteOffset,wasm.byteOffset+wasm.byteLength));rive.RuntimeLoader.setWasmFallbackUrl(null);
const runtime=await rive.RuntimeLoader.awaitInstance(),catalog=JSON.parse(fs.readFileSync(new URL('../visual/phase4/catalog.json',import.meta.url))),contract=JSON.parse(fs.readFileSync(new URL('../visual/phase2/body_contract.v2.json',import.meta.url))),generation=catalog.generation;
const file=await runtime.load(new Uint8Array(fs.readFileSync(new URL(`../output/visual-phase4/build/${generation}/jev_personality_v4.riv`,import.meta.url))),undefined,false);
const report={status:'PASS',runtime:'2.42.2 actual installed WASM',generation,tests:[],measurements:{},scope:'Finite numeric node samples; not analytical continuity or subjective superiority proof'};
function fixture(){const board=file.artboardByName(contract.artboard.name);let clock=0,tick,frame;const controller=createController({runtime,artboard:board,contract,catalog,now:()=>clock,subscribe(callback){tick=callback;return()=>{tick=null;};},onChange(event){if(event.type==='frame')frame=event;}});return{board,controller,at(t){clock=t;tick?.();},get frame(){return frame;},dispose(){controller.dispose();board.delete();}};}
const names=['BodyRoot','BodyDeform','Gaze','leftTilt','rightTilt','leftOpen','rightOpen','leftBlink','rightBlink'];
function pose(board){return names.flatMap(name=>{const n=board.node(name);return [n.x,n.y,n.rotation,n.scaleX,n.scaleY];});}
function jump(a,b){return Math.max(...a.map((v,i)=>Math.abs(v-b[i])));}
function recorded(name,fn){test(name,async()=>{try{await fn();report.tests.push(name);}catch(error){report.status='FAIL';report.failures??=[];report.failures.push({name,message:error.message});throw error;}});}
recorded('native envelope is Rive cubic, finite and flat at ends',()=>{const f=fixture(),clip=new runtime.LinearAnimationInstance(f.board.animationByName('playback_envelope'),f.board);const values=[];for(const t of [0,.001,.075,.149,.15]){clip.time=t;clip.advance(0);clip.apply(1);f.board.advance(0);values.push(f.board.node('PlaybackEnvelope').x);}assert.equal(values[0],1);assert.equal(values.at(-1),0);assert.ok(values.every(Number.isFinite));assert.ok(Math.abs(values[2]-.5)<1e-5);assert.ok(1-values[1]<.0002&&values[3]<.0002);report.measurements.envelope=values;clip.delete();f.dispose();});
recorded('all discovered native action variants animate finite nodes and finish neutral',async()=>{const f=fixture(),baseline=pose(f.board),cases=[];let t=0,max=0;for(const action of Object.values(catalog.actions))for(const variant of Object.keys(action.variants)){const handle=f.controller.play(action.id,{variant});let prior=pose(f.board);for(let elapsed=0;elapsed<=action.durationMs+150;elapsed+=1000/60){f.at(t+elapsed);const p=pose(f.board);assert.ok(p.every(Number.isFinite));max=Math.max(max,jump(prior,p));prior=p;}f.at(t+action.durationMs+151);assert.equal((await handle.finished).status,'completed');assert.ok(jump(baseline,pose(f.board))<1e-6);cases.push(`${action.id}:${variant}`);t+=action.durationMs+200;f.at(t);}report.measurements.nativeVariants={count:cases.length,cases,maxPerFrameMixedUnitNodeDisplacement:max};f.dispose();});
recorded('same-time command replacements preserve exact native pose and latest pending only',async()=>{const f=fixture();f.controller.setAmbient({bodyY:4,light:.8});f.controller.lookAt(-6,3);f.controller.play('hello');f.at(425);let before=pose(f.board),handle=f.controller.play('transform_star');let after=pose(f.board),maxJump=jump(before,after);assert.ok(maxJump<1e-5);f.at(470);before=pose(f.board);const last=f.controller.play('speech',{loop:true,variant:'bc'});after=pose(f.board);maxJump=Math.max(maxJump,jump(before,after));assert.ok(jump(before,after)<1e-5);assert.equal((await handle.finished).reason,'replaced');handle.cancel();assert.equal(f.frame.pendingOrders,1);assert.equal(f.frame.outgoingOwners,1);f.at(576);assert.equal(f.frame.action,'speech');last.cancel();f.at(730);assert.equal(f.frame.stage,'idle');report.measurements.sameTimeReplacementMaxJump=maxJump;f.dispose();});
recorded('1000 rapid orders retain one frozen outgoing owner and one latest pending order',async()=>{const f=fixture();f.controller.play('yes');f.at(300);let last;for(let i=0;i<1000;i++){const before=pose(f.board);last=f.controller.play(i%2?'transform_cloud':'no');assert.ok(jump(before,pose(f.board))<1e-5);assert.equal(f.frame.outgoingOwners,1);assert.equal(f.frame.pendingOrders,1);}f.at(451);assert.equal(f.frame.action,'transform_cloud');f.controller.stop();assert.equal((await last.finished).reason,'stopped');f.dispose();});
recorded('sustained duration is active wall time independent speed plus bounded recovery',async()=>{const results=[];for(const speed of [.1,1,4]){const f=fixture(),handle=f.controller.play('think',{durationMs:715,speed});f.at(714);assert.equal(f.frame.stage,'sustained');f.at(715);assert.equal(f.frame.stage,'recovery');f.at(864);assert.equal(f.frame.stage,'recovery');f.at(865);assert.equal((await handle.finished).status,'completed');assert.equal(f.frame.neutral,true);results.push({speed,activeMs:715,totalMs:865});f.dispose();}report.measurements.duration=results;});
recorded('native loop endpoints and sampled velocities match every sustained variant',()=>{const f=fixture(),cases=[];for(const a of Object.values(catalog.actions).filter(a=>a.behavior))for(const [variant,v]of Object.entries(a.variants)){const instance=new runtime.LinearAnimationInstance(f.board.animationByName(v.clip),f.board),b=a.behavior;function sample(t){f.controller.stop();instance.time=t/1000;instance.advance(0);instance.apply(1);f.board.advance(0);return pose(f.board);}const start=sample(b.cycleStartMs),end=sample(b.cycleEndMs),seam=jump(start,end);assert.ok(seam<1e-5);const dt=1,entryVelocity=jump(start,sample(b.cycleStartMs+dt))/dt,exitVelocity=jump(end,sample(b.cycleEndMs-dt))/dt;assert.ok(entryVelocity<.0003&&exitVelocity<.0003);cases.push({action:a.id,variant,seamMaxJump:seam,entryVelocityPerMs:entryVelocity,exitVelocityPerMs:exitVelocity});instance.delete();}report.measurements.loopSeams=cases;f.dispose();});
recorded('mid-entry and mid-cycle exits freeze native sampled pose without command jump',()=>{const cases=[];for(const [action,time]of [['think',85],['think',1100],['speech',650]]){const f=fixture(),handle=f.controller.play(action,{loop:true});f.at(time);const before=pose(f.board);handle.cancel();const change=jump(before,pose(f.board));assert.ok(change<1e-5);f.at(time+150);assert.equal(f.frame.neutral,true);cases.push({action,timeMs:time,commandJump:change});f.dispose();}report.measurements.exits=cases;});
recorded('overshoot traverses finite durations, recovery and sequence with no time loss',async()=>{const f=fixture(),handle=f.controller.sequence([{action:'think',durationMs:50,speed:4},{action:'speech',durationMs:300,speed:.1},'yes']);f.at(650);assert.equal(f.frame.action,'yes');assert.equal(f.frame.elapsedMs,0);f.at(1800);assert.equal((await handle.finished).completedItems,3);assert.equal(f.frame.neutral,true);f.dispose();});
recorded('invalid orders never mutate native pose, handles or schedule',async()=>{const f=fixture(),h=f.controller.play('think',{loop:true});f.at(800);const before=pose(f.board),frame=f.frame;for(const operation of [()=>f.controller.play('bad'),()=>f.controller.play('think',{durationMs:10,loop:false}),()=>f.controller.play('yes',{loop:true}),()=>f.controller.play('think',{speed:null}),()=>f.controller.play('speech',{durationMs:NaN}),()=>f.controller.sequence([{action:'think',loop:true}]),()=>f.controller.setAmbient({enabled:1}),()=>f.controller.setAmbient({seed:-1}),()=>f.controller.setAmbient({shapeTo:'star'}),()=>f.controller.lookAt(99,0)]){assert.throws(operation);assert.equal(f.frame,frame);assert.equal(jump(before,pose(f.board)),0);}f.controller.stop();assert.equal((await h.finished).reason,'stopped');f.dispose();});
recorded('ambient deterministic quiet occupancy and ownership release remain finite; stop clears scheduling',()=>{function run(){const f=fixture();f.controller.setAmbient({enabled:true,seed:731});const baseline=pose(f.board);let quiet=0,total=0,max=0;for(let t=0;t<=60000;t+=50){f.at(t);if(f.frame.ambientLayers.length===0){quiet++;assert.ok(jump(baseline,pose(f.board))<1e-6);}max=Math.max(max,jump(baseline,pose(f.board)));total++;}const result={schedule:f.frame.schedule,occupancy:f.frame.scheduledOccupancyMs,quietSampleFraction:quiet/total,maxNodeDifference:max};f.controller.play('yes');f.at(60400);f.controller.stop();const state=pose(f.board);f.at(120000);assert.equal(f.frame.neutral,true);assert.equal(f.frame.schedule.length,0);assert.equal(jump(state,pose(f.board)),0);f.dispose();return result;}const a=run(),b=run();assert.deepEqual(a,b);assert.ok(a.quietSampleFraction>.65);report.measurements.ambient=a;});
recorded('native ambient keeps numeric baseline, takeover/release continuous and amplitudes discreet',()=>{const f=fixture();f.controller.setAmbient({bodyY:4,bodyScaleY:1.03,light:.8});f.controller.lookAt(-5,3);f.controller.setAmbient({enabled:true,seed:731});assert.equal(f.frame.baseline.bodyY,4);assert.equal(f.frame.baseline.gazeX,-5);const start=7077.4751883000135;f.at(start+1400);const body=f.board.node('BodyRoot'),deform=f.board.node('BodyDeform');assert.ok(Math.abs(body.y-173.65)<.001);assert.ok(Math.abs(deform.scaleY-1.038)<.00001);const before=pose(f.board),handle=f.controller.play('hello');assert.ok(jump(before,pose(f.board))<1e-5);f.at(start+1550);handle.cancel();const atExit=pose(f.board);f.at(start+1550);assert.ok(jump(atExit,pose(f.board))<1e-5);let prior=atExit,max=0;for(let dt=1;dt<=150;dt++){f.at(start+1550+dt);const current=pose(f.board);max=Math.max(max,jump(prior,current));prior=current;}assert.ok(max<.15);assert.equal(f.frame.baseline.bodyY,4);assert.equal(f.frame.baseline.gazeX,-5);report.measurements.ambientBaseline={breathPeakBodyY:173.65,breathPeakScaleY:1.038,releaseMaxPerMsMixedUnitNodeDisplacement:max};f.controller.stop();f.controller.play('hello',{intensity:0});const zero=pose(f.board);f.at(start+2100);assert.equal(jump(zero,pose(f.board)),0);f.dispose();});
recorded('seeded ambient sparse and dense clocks match exact schedule occupancy and native final pose',()=>{function run(dense){const f=fixture();f.controller.setAmbient({enabled:true,seed:731});if(dense)for(let t=100;t<600000;t+=100)f.at(t);f.at(600000);const result={schedule:f.frame.schedule,occupancy:f.frame.scheduledOccupancyMs,layers:f.frame.ambientLayers,pose:pose(f.board)};f.dispose();return result;}const dense=run(true),sparse=run(false);assert.deepEqual(sparse,dense);report.measurements.cadenceIndependentAmbient={horizonMs:600000,denseTickMs:100,sparseTicks:1,exact:true,occupancy:dense.occupancy,retainedScheduleEvents:dense.schedule.length};});
test.after(()=>{fs.writeFileSync(new URL('../output/visual-phase4/native-validation.json',import.meta.url),JSON.stringify(report,null,2)+'\n');file.unref();runtime.cleanup?.();});
