import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {createController} from '../visual/phase4/web/controller.mjs';
const require=createRequire(import.meta.url),rive=require('../../node_modules/@rive-app/webgl2/rive.js');
const wasm=fs.readFileSync(new URL('../../node_modules/@rive-app/webgl2/rive.wasm',import.meta.url));rive.RuntimeLoader.setWasmBinary(wasm.buffer.slice(wasm.byteOffset,wasm.byteOffset+wasm.byteLength));rive.RuntimeLoader.setWasmFallbackUrl(null);
const runtime=await rive.RuntimeLoader.awaitInstance(),catalog=JSON.parse(fs.readFileSync(new URL('../visual/phase4/catalog.json',import.meta.url))),contract=JSON.parse(fs.readFileSync(new URL('../visual/phase2/body_contract.v2.json',import.meta.url))),generation=catalog.generation;
const file=await runtime.load(new Uint8Array(fs.readFileSync(new URL(`../output/visual-phase4/build/${generation}/jev_personality_v4.riv`,import.meta.url))),undefined,false);
const report={status:'PASS',runtime:'2.42.2 actual installed WASM',generation,expectedGroups:0,tests:[],measurements:{},scope:'Finite numeric node samples; not analytical continuity or subjective superiority proof'};
function fixture({ambient=false}={}){const board=file.artboardByName(contract.artboard.name);let clock=0,tick,frame;const controller=createController({runtime,artboard:board,contract,catalog,now:()=>clock,subscribe(callback){tick=callback;return()=>{tick=null;};},onChange(event){if(event.type==='frame')frame=event;}});if(!ambient)controller.setAmbient({enabled:false});return{board,controller,at(t){clock=t;tick?.();},get frame(){return frame;},dispose(){controller.dispose();board.delete();}};}
const names=['BodyRoot','BumpTransform','BodyDeform','Gaze','leftTilt','rightTilt','leftOpen','rightOpen','leftBlink','rightBlink'];
function pose(board){return names.flatMap(name=>{const n=board.node(name);return [n.x,n.y,n.rotation,n.scaleX,n.scaleY];});}
function jump(a,b){return Math.max(...a.map((v,i)=>Math.abs(v-b[i])));}
function recorded(name,fn){report.expectedGroups++;test(name,async()=>{try{await fn();report.tests.push(name);}catch(error){report.status='FAIL';report.failures??=[];report.failures.push({name,message:error.message});throw error;}});}
recorded('native envelope is Rive cubic, finite and flat at ends',()=>{const f=fixture(),clip=new runtime.LinearAnimationInstance(f.board.animationByName('playback_envelope'),f.board);const values=[];for(const t of [0,.001,.075,.149,.15]){clip.time=t;clip.advance(0);clip.apply(1);f.board.advance(0);values.push(f.board.node('PlaybackEnvelope').x);}assert.equal(values[0],1);assert.equal(values.at(-1),0);assert.ok(values.every(Number.isFinite));assert.ok(Math.abs(values[2]-.5)<1e-5);assert.ok(1-values[1]<.0002&&values[3]<.0002);report.measurements.envelope=values;clip.delete();f.dispose();});
recorded('default idle continuously breathes, opens eyes slightly and drifts gaze',()=>{const f=fixture({ambient:true});assert.equal(f.frame.stage,'idle');assert.equal(f.frame.ambientEnabled,true);let peak;for(let t=0;t<=10000;t+=100){f.at(t);assert.ok(f.frame.ambientLayers.some(layer=>layer.kind==='breath'),`breath gap at ${t}ms`);if(t===1400){const deform=f.board.node('BodyDeform'),gaze=f.board.node('Gaze'),left=f.board.node('leftOpen'),right=f.board.node('rightOpen');assert.ok(deform.scaleX>1.02&&deform.scaleY>1.04);assert.ok(gaze.x<-.9);assert.ok(left.scaleY>1.05&&right.scaleY>1.05);peak={scaleX:deform.scaleX,scaleY:deform.scaleY,gazeX:gaze.x,leftOpen:left.scaleY,rightOpen:right.scaleY};}if(t===2800){assert.ok(Math.abs(f.board.node('BodyDeform').scaleX-1)<1e-6&&Math.abs(f.board.node('BodyDeform').scaleY-1)<1e-6);assert.ok(Math.abs(f.board.node('Gaze').x)<1e-6);}}f.at(60000);assert.ok(f.frame.schedule.some(event=>event.kind==='blink'));report.measurements.continuousIdle={peak,breathCoverage:1,blinkEvents:f.frame.schedule.filter(event=>event.kind==='blink').length};f.dispose();});
recorded('Rive bump is visible before the gesture and after recovery',async()=>{const f=fixture(),handle=f.controller.play('yes');f.at(100);const entryScale=f.board.node('BumpTransform').scaleX;assert.ok(Math.abs(entryScale-1.08)<1e-6);assert.equal(f.frame.clipTimeMs,0);assert.equal(f.frame.elapsedMs,0);assert.equal(f.board.node('BodyRoot').y,170);f.at(250);assert.equal(f.board.node('BumpTransform').scaleX,1);assert.equal(f.frame.stage,'action');f.at(1650);assert.equal(f.frame.stage,'recovery');f.at(1800);assert.equal(f.frame.transition.kind,'return');f.at(1900);const returnScale=f.board.node('BumpTransform').scaleX;assert.ok(Math.abs(returnScale-1.08)<1e-6);f.at(2050);assert.equal((await handle.finished).status,'completed');assert.equal(f.frame.stage,'idle');report.measurements.bump={entryPeakScale:entryScale,returnPeakScale:returnScale,preGestureMs:250,returnAfterRecovery:true};f.dispose();});
recorded('dispose resets an in-flight bump before releasing its rig',()=>{const f=fixture();f.controller.play('hello');f.at(80);assert.ok(f.board.node('BumpTransform').scaleX>1.025);f.controller.dispose();assert.equal(f.board.node('BumpTransform').scaleX,1);assert.equal(f.board.node('BumpTransform').scaleY,1);f.dispose();});
recorded('composed scales and circular halo stay inside the rig at extreme speeds',async()=>{const cases=[];for(const id of ['yes','think','transform_star'])for(const speed of [.1,4]){const f=fixture({ambient:true}),handle=f.controller.play(id,{speed}),end=catalog.actions[id].durationMs/speed+650;let maxX=1,maxY=1,maxExtent=0;for(let t=0;t<=end;t+=10){f.at(t);const deform=f.board.node('BodyDeform'),bump=f.board.node('BumpTransform'),body=f.board.node('BodyRoot'),x=deform.scaleX*bump.scaleX,y=deform.scaleY*bump.scaleY;assert.ok(x<=1.120001&&y<=1.120001);const extent=121*Math.max(x,y)+Math.max(Math.abs(body.x-180),Math.abs(body.y-170));assert.ok(extent<170);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);maxExtent=Math.max(maxExtent,extent);}f.at(end+1);assert.equal((await handle.finished).status,'completed');cases.push({id,speed,maxX,maxY,maxHaloExtent:maxExtent});f.dispose();}report.measurements.extremeComposition=cases;});
recorded('all discovered native action variants animate finite nodes and finish neutral',async()=>{const f=fixture(),baseline=pose(f.board),cases=[];let t=0,max=0;for(const action of Object.values(catalog.actions))for(const variant of Object.keys(action.variants)){const handle=f.controller.play(action.id,{variant});let prior=pose(f.board);for(let elapsed=0;elapsed<=action.durationMs+650;elapsed+=1000/60){f.at(t+elapsed);const p=pose(f.board);assert.ok(p.every(Number.isFinite));max=Math.max(max,jump(prior,p));prior=p;}f.at(t+action.durationMs+651);assert.equal((await handle.finished).status,'completed');assert.ok(jump(baseline,pose(f.board))<1e-6);cases.push(`${action.id}:${variant}`);t+=action.durationMs+700;f.at(t);}report.measurements.nativeVariants={count:cases.length,cases,maxPerFrameMixedUnitNodeDisplacement:max};f.dispose();});
recorded('same-time command replacements preserve exact native pose and latest pending only',async()=>{const f=fixture();f.controller.setAmbient({bodyY:4,light:.8});f.controller.lookAt(-6,3);f.controller.play('hello');f.at(425);let before=pose(f.board),handle=f.controller.play('transform_star');let after=pose(f.board),maxJump=jump(before,after);assert.ok(maxJump<1e-5);f.at(470);before=pose(f.board);const last=f.controller.play('speech',{loop:true,variant:'bc'});after=pose(f.board);maxJump=Math.max(maxJump,jump(before,after));assert.ok(jump(before,after)<1e-5);assert.equal((await handle.finished).reason,'replaced');handle.cancel();assert.equal(f.frame.pendingOrders,1);assert.equal(f.frame.outgoingOwners,1);f.at(576);assert.equal(f.frame.action,'speech');last.cancel();f.at(976);assert.equal(f.frame.stage,'idle');report.measurements.sameTimeReplacementMaxJump=maxJump;f.dispose();});
recorded('replacement during a live bump preserves the current pose and bumps the successor',async()=>{const f=fixture(),first=f.controller.play('hello');f.at(50);const before=pose(f.board),next=f.controller.play('no');assert.ok(jump(before,pose(f.board))<1e-5);assert.equal((await first.finished).reason,'replaced');f.at(200);assert.equal(f.frame.action,'no');assert.equal(f.frame.pendingOrders,0);assert.equal(f.frame.transition.kind,'entry');f.at(300);const peak=f.board.node('BumpTransform').scaleX;assert.ok(peak>1.079);const beforeCancel=pose(f.board);next.cancel();assert.ok(jump(beforeCancel,pose(f.board))<1e-5);f.at(700);assert.equal(f.frame.stage,'idle');report.measurements.liveBumpReplacement={successorBumpScale:peak,noCommandJump:true};f.dispose();});
recorded('1000 rapid orders retain one frozen outgoing owner and one latest pending order',async()=>{const f=fixture();f.controller.play('yes');f.at(300);let last;for(let i=0;i<1000;i++){const before=pose(f.board);last=f.controller.play(i%2?'transform_cloud':'no');assert.ok(jump(before,pose(f.board))<1e-5);assert.equal(f.frame.outgoingOwners,1);assert.equal(f.frame.pendingOrders,1);}f.at(451);assert.equal(f.frame.action,'transform_cloud');f.controller.stop();assert.equal((await last.finished).reason,'stopped');f.dispose();});
recorded('sustained duration excludes transition clocks and is independent of speed',async()=>{const results=[];for(const speed of [.1,1,4]){const f=fixture(),handle=f.controller.play('think',{durationMs:715,speed});f.at(249);assert.equal(f.frame.stage,'entry');f.at(964);assert.equal(f.frame.stage,'sustained');f.at(965);assert.equal(f.frame.stage,'recovery');f.at(1115);assert.equal(f.frame.stage,'return');f.at(1365);assert.equal((await handle.finished).status,'completed');assert.equal(f.frame.neutral,true);results.push({speed,activeMs:715,totalMs:1365});f.dispose();}report.measurements.duration=results;});
recorded('native loop endpoints and sampled velocities match every sustained variant',()=>{const f=fixture(),cases=[];for(const a of Object.values(catalog.actions).filter(a=>a.behavior))for(const [variant,v]of Object.entries(a.variants)){const instance=new runtime.LinearAnimationInstance(f.board.animationByName(v.clip),f.board),b=a.behavior;function sample(t){f.controller.stop();instance.time=t/1000;instance.advance(0);instance.apply(1);f.board.advance(0);return pose(f.board);}const start=sample(b.cycleStartMs),end=sample(b.cycleEndMs),seam=jump(start,end);assert.ok(seam<1e-5);const dt=1,entryVelocity=jump(start,sample(b.cycleStartMs+dt))/dt,exitVelocity=jump(end,sample(b.cycleEndMs-dt))/dt;assert.ok(entryVelocity<.0003&&exitVelocity<.0003);cases.push({action:a.id,variant,seamMaxJump:seam,entryVelocityPerMs:entryVelocity,exitVelocityPerMs:exitVelocity});instance.delete();}report.measurements.loopSeams=cases;f.dispose();});
recorded('mid-entry and mid-cycle exits freeze native sampled pose without command jump',()=>{const cases=[];for(const [action,time]of [['think',85],['think',1100],['speech',650]]){const f=fixture(),handle=f.controller.play(action,{loop:true});f.at(time);const before=pose(f.board);handle.cancel();const change=jump(before,pose(f.board));assert.ok(change<1e-5);f.at(time+400);assert.equal(f.frame.neutral,true);cases.push({action,timeMs:time,commandJump:change});f.dispose();}report.measurements.exits=cases;});
recorded('overshoot traverses entry, finite durations, recovery and sequence without time loss',async()=>{const f=fixture(),handle=f.controller.sequence([{action:'think',durationMs:50,speed:4},{action:'speech',durationMs:300,speed:.1},'yes']);f.at(1150);assert.equal(f.frame.action,'yes');assert.equal(f.frame.stage,'entry');assert.equal(f.frame.elapsedMs,0);f.at(1400);assert.equal(f.frame.stage,'action');f.at(3200);assert.equal((await handle.finished).completedItems,3);assert.equal(f.frame.neutral,true);f.dispose();});
recorded('invalid orders never mutate native pose, handles or schedule',async()=>{const f=fixture(),h=f.controller.play('think',{loop:true});f.at(800);const before=pose(f.board),frame=f.frame;for(const operation of [()=>f.controller.play('bad'),()=>f.controller.play('think',{durationMs:10,loop:false}),()=>f.controller.play('yes',{loop:true}),()=>f.controller.play('think',{speed:null}),()=>f.controller.play('speech',{durationMs:NaN}),()=>f.controller.sequence([{action:'think',loop:true}]),()=>f.controller.setAmbient({enabled:1}),()=>f.controller.setAmbient({seed:-1}),()=>f.controller.setAmbient({shapeTo:'star'}),()=>f.controller.lookAt(99,0)]){assert.throws(operation);assert.equal(f.frame,frame);assert.equal(jump(before,pose(f.board)),0);}f.controller.stop();assert.equal((await h.finished).reason,'stopped');f.dispose();});
recorded('continuous ambient stays active while preserving deterministic scheduling and stop clears it',()=>{function run(){const f=fixture({ambient:true}),baseline=pose(f.board);let max=0,total=0;for(let t=0;t<=60000;t+=50){f.at(t);assert.ok(f.frame.ambientLayers.some(layer=>layer.kind==='breath'),`breath gap at ${t}ms`);max=Math.max(max,jump(baseline,pose(f.board)));total++;}const result={schedule:f.frame.schedule,occupancy:f.frame.scheduledOccupancyMs,breathCoverage:total/(60000/50+1),maxNodeDifference:max};f.controller.play('yes');f.at(60400);f.controller.stop();const state=pose(f.board);f.at(120000);assert.equal(f.frame.neutral,true);assert.equal(f.frame.schedule.length,0);assert.equal(jump(state,pose(f.board)),0);f.dispose();return result;}const a=run(),b=run();assert.deepEqual(a,b);assert.equal(a.breathCoverage,1);assert.ok(a.maxNodeDifference>.02);report.measurements.ambient=a;});
recorded('native ambient composes eye/body channels over a saved numeric baseline',()=>{const f=fixture({ambient:true});f.controller.setAmbient({bodyY:4,bodyScaleY:1.03,light:.8});f.controller.lookAt(-5,3);f.controller.setAmbient({enabled:true,seed:731});assert.equal(f.frame.baseline.bodyY,4);assert.equal(f.frame.baseline.gazeX,-5);f.at(1400);const body=f.board.node('BodyRoot'),deform=f.board.node('BodyDeform');assert.ok(Math.abs(body.y-173.55)<.001);assert.ok(Math.abs(deform.scaleY-1.075)<.00001);const before=pose(f.board),handle=f.controller.play('hello');assert.ok(jump(before,pose(f.board))<1e-5);f.at(1550);handle.cancel();const atExit=pose(f.board);f.at(1550);assert.ok(jump(atExit,pose(f.board))<1e-5);let prior=atExit,max=0;for(let dt=1;dt<=150;dt++){f.at(1550+dt);const current=pose(f.board);max=Math.max(max,jump(prior,current));prior=current;}assert.ok(max<.15);assert.equal(f.frame.baseline.bodyY,4);assert.equal(f.frame.baseline.gazeX,-5);report.measurements.ambientBaseline={breathPeakBodyY:173.55,breathPeakScaleY:1.075,releaseMaxPerMsMixedUnitNodeDisplacement:max};f.controller.stop();f.controller.play('hello',{intensity:0});const zero=pose(f.board);f.at(2100);assert.equal(jump(zero,pose(f.board)),0);f.dispose();});
recorded('seeded ambient sparse and dense clocks match exact schedule occupancy and native final pose',()=>{function run(dense){const f=fixture();f.controller.setAmbient({enabled:true,seed:731});if(dense)for(let t=100;t<600000;t+=100)f.at(t);f.at(600000);const result={schedule:f.frame.schedule,occupancy:f.frame.scheduledOccupancyMs,layers:f.frame.ambientLayers,pose:pose(f.board)};f.dispose();return result;}const dense=run(true),sparse=run(false);assert.deepEqual(sparse,dense);report.measurements.cadenceIndependentAmbient={horizonMs:600000,denseTickMs:100,sparseTicks:1,exact:true,occupancy:dense.occupancy,retainedScheduleEvents:dense.schedule.length};});
recorded('controller visibly applies each prototype after the pre-gesture bump',async()=>{
  const measurements=[];
  for(const id of ['yes','think','transform_star']){
    const f=fixture(),baseline=pose(f.board),h=f.controller.play(id),samples=[];let maximumChange=0;
    for(let elapsed=0;elapsed<=catalog.actions[id].durationMs;elapsed+=1000/60){
      f.at(250+elapsed);assert.equal(f.frame.transition,null);assert.ok(Math.abs(f.frame.playing.mix-1)<1e-6);
      const current=pose(f.board),body=f.board.node('BodyRoot'),deform=f.board.node('BodyDeform'),gaze=f.board.node('Gaze');
      maximumChange=Math.max(maximumChange,jump(baseline,current));
      samples.push({activeMs:elapsed,bodyX:body.x-180,bodyY:body.y-170,scaleX:deform.scaleX,scaleY:deform.scaleY,gazeX:gaze.x,gazeY:gaze.y});
    }
    assert.ok(maximumChange>=7,`${id}: no legible body/eye gesture`);
    if(id==='yes'){assert.ok(Math.min(...samples.map(s=>s.bodyY))<=-8.9);assert.ok(Math.max(...samples.map(s=>s.bodyY))>=9.9);}
    if(id==='think'){assert.ok(Math.min(...samples.map(s=>s.gazeX))<=-6.9);assert.ok(Math.max(...samples.map(s=>s.gazeX))>=5.9);}
    f.at(catalog.actions[id].durationMs+650);assert.equal((await h.finished).status,'completed');
    measurements.push({id,maximumNodeChange:maximumChange,samples});f.dispose();
  }
  report.measurements.visibleControllerPrototypes=measurements;
});
recorded('prototype lifecycle matrix covers replacement cancellation Stop and disposal in each transition',async()=>{
  const cases=[];
  for(const id of ['yes','think','transform_star'])for(const speed of [.1,1,4]){
    const duration=catalog.actions[id].durationMs/speed;
    const times={entry:100,gesture:250+duration/2,recovery:250+duration+75,return:250+duration+250};
    for(const [stage,t]of Object.entries(times))for(const operation of ['replace','cancel','stop','dispose']){
      const f=fixture(),baseline=pose(f.board),h=f.controller.play(id,{speed});f.at(t);
      assert.equal(f.frame.stage,stage==='gesture'?'action':stage);
      const before=pose(f.board);let next;
      if(operation==='replace')next=f.controller.play('think',{loop:true});
      else if(operation==='cancel')h.cancel();
      else f.controller[operation]();
      const delta=jump(before,pose(f.board));
      if(operation==='replace'||operation==='cancel')assert.ok(delta<1e-5,`${id}/${speed}/${stage}/${operation}: ${delta}`);
      else assert.ok(jump(baseline,pose(f.board))<1e-6);
      assert.equal((await h.finished).status,'cancelled');
      if(operation!=='dispose'){f.at(t+1000);if(next){assert.equal(f.frame.action,'think');assert.equal(f.frame.pendingOrders,0);f.controller.stop();assert.equal((await next.finished).reason,'stopped');}else assert.equal(f.frame.stage,'idle');}
      cases.push({id,speed,stage,operation,commandJump:delta});f.dispose();
    }
  }
  report.measurements.lifecycleMatrix=cases;
});
recorded('zero intensity preserves numeric baseline and live idle through the complete lifecycle',async()=>{
  const cases=[];
  for(const id of ['yes','think','transform_star']){
    const f=fixture({ambient:true}),reference=fixture({ambient:true});
    for(const x of [f,reference]){x.controller.setAmbient({bodyScaleX:1.1,bodyY:4});x.controller.lookAt(-6,3);}
    const h=f.controller.play(id,{intensity:0,speed:4}),end=catalog.actions[id].durationMs/4+650;let max=0;
    for(let t=0;t<=end;t+=25){f.at(t);reference.at(t);max=Math.max(max,jump(pose(f.board),pose(reference.board)));}
    assert.ok(max<1e-5,`${id} zero-intensity ambient delta ${max}`);f.at(end+1);assert.equal((await h.finished).status,'completed');cases.push({id,maxPoseDifference:max});f.dispose();reference.dispose();
  }
  report.measurements.zeroIntensity=cases;
});
test.after(()=>{report.complete=report.tests.length===report.expectedGroups;if(!report.complete&&report.status==='PASS')report.status='PARTIAL';fs.writeFileSync(new URL('../output/visual-phase4/native-validation.json',import.meta.url),JSON.stringify(report,null,2)+'\n');file.unref();runtime.cleanup?.();});
