import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createController}from'../visual/phase4/web/controller.mjs';
const contract=JSON.parse(fs.readFileSync(new URL('../visual/phase2/body_contract.v2.json',import.meta.url))),catalog=JSON.parse(fs.readFileSync(new URL('../visual/phase4/catalog.json',import.meta.url)));
function fixture({missing,failSubscribe=false,invalidCleanup=false,failReport=false,ambient=false}={}){const instances=[],changes=[],nodes=new Map();let clock=0,tick,unsubscribed=0;class Instance{constructor(name){this.name=name;this.deleted=0;instances.push(this);}advance(){}apply(){if(this.name==='playback_envelope')node('PlaybackEnvelope').x=Math.max(0,1-this.time/.15);}delete(){this.deleted++;}}function node(name){if(!nodes.has(name))nodes.set(name,{x:name==='PlaybackEnvelope'?1:0,y:170,rotation:0,scaleX:1,scaleY:1});return nodes.get(name);}const board={animationByName:name=>name===missing?null:name,node,advance(){}};return{instances,changes,get unsubscribed(){return unsubscribed;},create(){const controller=createController({runtime:{LinearAnimationInstance:Instance},artboard:board,contract,catalog,now:()=>clock,subscribe(callback){if(failSubscribe)throw Error('subscription failed');tick=callback;return invalidCleanup?null:()=>{tick=null;unsubscribed++;};},onChange(event){if(failReport)throw Error('report failed');changes.push(event);}});if(!ambient)controller.setAmbient({enabled:false});return controller;},at(t){clock=t;tick?.();},get frame(){return changes.findLast(e=>e.type==='frame');}};}
test('constructor partial missing clip deletes every created native instance once',()=>{for(const missing of ['channel_gazeY','ambient_breath__bodyY','action_speech__bc']){const f=fixture({missing});assert.throws(()=>f.create(),/Clip/);assert.ok(f.instances.length>0);assert.ok(f.instances.every(x=>x.deleted===1));}});
test('subscription failure and invalid cleanup release every created instance once',()=>{for(const options of [{failSubscribe:true},{invalidCleanup:true},{failReport:true}]){const f=fixture(options);assert.throws(()=>f.create());assert.ok(f.instances.every(x=>x.deleted===1));}});
test('default idle is active immediately and continuous breath never leaves a scheduling gap',()=>{const f=fixture({ambient:true}),c=f.create();assert.equal(f.frame.stage,'idle');assert.equal(f.frame.ambientEnabled,true);for(let t=0;t<=10000;t+=100){f.at(t);assert.ok(f.frame.ambientLayers.some(layer=>layer.kind==='breath'),`missing breath at ${t}ms`);}assert.equal(f.frame.pendingOrders,0);c.dispose();});
test('entry bump precedes active time and return bump follows settle',async()=>{const f=fixture(),c=f.create(),handle=c.play('hello');assert.equal(f.frame.stage,'entry');f.at(249);assert.equal(f.frame.elapsedMs,0);assert.equal(f.frame.clipTimeMs,0);f.at(250);assert.equal(f.frame.stage,'action');assert.equal(f.frame.transition,null);f.at(1450);assert.equal(f.frame.stage,'recovery');f.at(1600);assert.equal(f.frame.stage,'return');assert.equal(f.frame.transition.kind,'return');f.at(1850);assert.equal((await handle.finished).status,'completed');assert.equal(f.frame.stage,'idle');assert.equal(f.frame.transition,null);assert.equal(f.frame.neutral,true);c.dispose();});
test('replacement enters through one bump without retaining a queued action',async()=>{const f=fixture(),c=f.create(),old=c.play('hello');f.at(300);const next=c.play('no');assert.equal((await old.finished).reason,'replaced');assert.equal(f.frame.pendingOrders,1);f.at(449);assert.equal(f.frame.action,null);f.at(450);assert.equal(f.frame.action,'no');assert.equal(f.frame.transition.kind,'entry');assert.equal(f.frame.pendingOrders,0);c.stop();assert.equal((await next.finished).reason,'stopped');c.dispose();});
test('public interface six commands and idempotent disposal, stale handle remains harmless',async()=>{const f=fixture(),c=f.create();assert.deepEqual(Object.keys(c).sort(),['dispose','lookAt','play','sequence','setAmbient','stop']);const old=c.play('hello');f.at(250);const next=c.play('no');assert.equal((await old.finished).reason,'replaced');old.cancel();assert.equal(f.frame.pendingOrders,1);c.dispose();c.dispose();assert.equal((await next.finished).reason,'disposed');assert.equal(f.unsubscribed,1);assert.ok(f.instances.every(x=>x.deleted===1));assert.throws(()=>c.stop(),/disposed/);const count=f.changes.length;f.at(999);assert.equal(f.changes.length,count);});
test('stop during recovery drops outgoing pending ambient and later ticks stay exactly neutral',async()=>{const f=fixture(),c=f.create();c.setAmbient({enabled:true,seed:731});c.play('yes');f.at(250);const last=c.play('transform_ghost');assert.equal(f.frame.outgoingOwners,1);c.stop();assert.equal((await last.finished).reason,'stopped');assert.equal(f.frame.outgoingOwners,0);assert.equal(f.frame.pendingOrders,0);assert.equal(f.frame.ambientEnabled,false);f.at(1e6);assert.equal(f.frame.neutral,true);assert.equal(f.frame.schedule.length,0);c.dispose();});
test('explicit null and invalid ambient/sustained values mutate nothing',()=>{const f=fixture(),c=f.create();c.play('speech',{loop:true});f.at(10);const frame=f.frame,count=f.changes.length;for(const command of [()=>c.play('speech',{intensity:null}),()=>c.play('speech',{loop:null}),()=>c.play('speech',{durationMs:null}),()=>c.play('speech',{durationMs:1,loop:false}),()=>c.setAmbient({seed:1.1}),()=>c.setAmbient({enabled:null}),()=>c.sequence([{action:'speech',durationMs:1},{action:'unknown'}])]){assert.throws(command);assert.equal(f.frame,frame);assert.equal(f.changes.length,count);}c.dispose();});
test('zero intensity still completes active duration plus entry recovery and return',async()=>{const f=fixture(),c=f.create(),h=c.play('speech',{durationMs:50,speed:.1,intensity:0});f.at(25);assert.equal(f.frame.playing.mix,0);f.at(699);assert.equal(f.frame.stage,'return');f.at(700);assert.equal((await h.finished).status,'completed');assert.equal(f.frame.neutral,true);c.dispose();});
